<CaptureBox>:
	task_input: task_input
	orientation: 'horizontal'
	height: 5
	
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

	TextInput:
		id: task_input
		size_hint_x: 0.8
		multiline: False
		focus: True
		font_size: dp(24)
		on_text_validate: root.on_submit(); app.stop()
		
	AsyncImage:
		size_hint_x: .08
		source: 'assets/smallcorgi.png'
		allow_stretch: True